ARG BASE_IMAGE=sbtscala/sbt:1.10.7_2.13.15_3
FROM ${BASE_IMAGE}
ARG PERSONALIZATION_USERNAME
RUN useradd -m -s /bin/bash "${PERSONALIZATION_USERNAME}" && \
    mkdir -p "/home/${PERSONALIZATION_USERNAME}/.sbt" "/home/${PERSONALIZATION_USERNAME}/.ivy2" && \
    chown -R "${PERSONALIZATION_USERNAME}:${PERSONALIZATION_USERNAME}" "/home/${PERSONALIZATION_USERNAME}"
USER ${PERSONALIZATION_USERNAME}
WORKDIR /work
ENTRYPOINT ["sbt"]
